/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhsCommitmentRouteImport } from './routes/whs-commitment'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as JobSeekersRouteImport } from './routes/job-seekers'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as EqualOpportunityRouteImport } from './routes/equal-opportunity'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as EmployerEnquiryRouteImport } from './routes/employer-enquiry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CandidatePrivacyNoticeRouteImport } from './routes/candidate-privacy-notice'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'

const WhsCommitmentRoute = WhsCommitmentRouteImport.update({
  id: '/whs-commitment',
  path: '/whs-commitment',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobSeekersRoute = JobSeekersRouteImport.update({
  id: '/job-seekers',
  path: '/job-seekers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const EqualOpportunityRoute = EqualOpportunityRouteImport.update({
  id: '/equal-opportunity',
  path: '/equal-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerEnquiryRoute = EmployerEnquiryRouteImport.update({
  id: '/employer-enquiry',
  path: '/employer-enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePrivacyNoticeRoute = CandidatePrivacyNoticeRouteImport.update({
  id: '/candidate-privacy-notice',
  path: '/candidate-privacy-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/candidate-privacy-notice': typeof CandidatePrivacyNoticeRoute
  '/contact': typeof ContactRoute
  '/employer-enquiry': typeof EmployerEnquiryRoute
  '/employers': typeof EmployersRoute
  '/equal-opportunity': typeof EqualOpportunityRoute
  '/industries': typeof IndustriesRoute
  '/job-seekers': typeof JobSeekersRoute
  '/jobs': typeof JobsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/whs-commitment': typeof WhsCommitmentRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/candidate-privacy-notice': typeof CandidatePrivacyNoticeRoute
  '/contact': typeof ContactRoute
  '/employer-enquiry': typeof EmployerEnquiryRoute
  '/employers': typeof EmployersRoute
  '/equal-opportunity': typeof EqualOpportunityRoute
  '/industries': typeof IndustriesRoute
  '/job-seekers': typeof JobSeekersRoute
  '/jobs': typeof JobsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/whs-commitment': typeof WhsCommitmentRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/candidate-privacy-notice': typeof CandidatePrivacyNoticeRoute
  '/contact': typeof ContactRoute
  '/employer-enquiry': typeof EmployerEnquiryRoute
  '/employers': typeof EmployersRoute
  '/equal-opportunity': typeof EqualOpportunityRoute
  '/industries': typeof IndustriesRoute
  '/job-seekers': typeof JobSeekersRoute
  '/jobs': typeof JobsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/whs-commitment': typeof WhsCommitmentRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/candidate-privacy-notice'
    | '/contact'
    | '/employer-enquiry'
    | '/employers'
    | '/equal-opportunity'
    | '/industries'
    | '/job-seekers'
    | '/jobs'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/whs-commitment'
    | '/admin/applications'
    | '/admin/jobs'
    | '/admin/login'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/candidate-privacy-notice'
    | '/contact'
    | '/employer-enquiry'
    | '/employers'
    | '/equal-opportunity'
    | '/industries'
    | '/job-seekers'
    | '/jobs'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/whs-commitment'
    | '/admin/applications'
    | '/admin/jobs'
    | '/admin/login'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/candidate-privacy-notice'
    | '/contact'
    | '/employer-enquiry'
    | '/employers'
    | '/equal-opportunity'
    | '/industries'
    | '/job-seekers'
    | '/jobs'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/whs-commitment'
    | '/admin/applications'
    | '/admin/jobs'
    | '/admin/login'
    | '/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  CandidatePrivacyNoticeRoute: typeof CandidatePrivacyNoticeRoute
  ContactRoute: typeof ContactRoute
  EmployerEnquiryRoute: typeof EmployerEnquiryRoute
  EmployersRoute: typeof EmployersRoute
  EqualOpportunityRoute: typeof EqualOpportunityRoute
  IndustriesRoute: typeof IndustriesRoute
  JobSeekersRoute: typeof JobSeekersRoute
  JobsRoute: typeof JobsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  WhsCommitmentRoute: typeof WhsCommitmentRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whs-commitment': {
      id: '/whs-commitment'
      path: '/whs-commitment'
      fullPath: '/whs-commitment'
      preLoaderRoute: typeof WhsCommitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-seekers': {
      id: '/job-seekers'
      path: '/job-seekers'
      fullPath: '/job-seekers'
      preLoaderRoute: typeof JobSeekersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equal-opportunity': {
      id: '/equal-opportunity'
      path: '/equal-opportunity'
      fullPath: '/equal-opportunity'
      preLoaderRoute: typeof EqualOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-enquiry': {
      id: '/employer-enquiry'
      path: '/employer-enquiry'
      fullPath: '/employer-enquiry'
      preLoaderRoute: typeof EmployerEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-privacy-notice': {
      id: '/candidate-privacy-notice'
      path: '/candidate-privacy-notice'
      fullPath: '/candidate-privacy-notice'
      preLoaderRoute: typeof CandidatePrivacyNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  CandidatePrivacyNoticeRoute: CandidatePrivacyNoticeRoute,
  ContactRoute: ContactRoute,
  EmployerEnquiryRoute: EmployerEnquiryRoute,
  EmployersRoute: EmployersRoute,
  EqualOpportunityRoute: EqualOpportunityRoute,
  IndustriesRoute: IndustriesRoute,
  JobSeekersRoute: JobSeekersRoute,
  JobsRoute: JobsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  WhsCommitmentRoute: WhsCommitmentRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
